### ISSUE TITLE
Software crashes if the LED values are deleted using backspace button

### ISSUE THREAD

**Issue by mtorkashvand** [venkatachalamlab/OpenAutoScope-v2#1]
Reproduce:
Turn on the 470nm LED, to change the power percentage, delete the current value using backspace button

![Capture](https://github.com/venkatachalamlab/OpenAutoScope-v2/assets/31863323/b696078b-e32d-4e3f-b512-570e5029eff3)

**Comment by mtorkashvand** [comment]
When does `add_state` get called?
Is it when you press 'Enter'?

the reason I am asking this question is because I think the following is a common way to set some parameter:

- the laser intensity has some value (double-digit like 15%)
- user wants to change that to another value, say 25%
- user uses `backspace` twice, once to remove 5 and the second time to remove 1 
- user inputs 2 followed by 5
- user presses 'Enter'

if `add_state` is called whenever a changes happens then in this case, the power does not go from 15 to 25 (which is what user wants). first it changes from 15 % to 1% then it changes from 1% to whatever the lower bound is then it changes from the lower bound to 2% and finally from 2% to 25% which is not what the user intended.

So I was thinking the fix for this is to make sure it only updates the value if 'Enter' is pressed.

**Comment by SinRas** [comment]
@mtorkashvand 
The element [Return Handler](https://github.com/venkatachalamlab/OpenAutoScope-v2/blob/main/openautoscopev2/ui/elements.py#L81-L107) is responsible for detection of 'return/enter key press'.  
The element [InputAutoselect](https://github.com/venkatachalamlab/OpenAutoScope-v2/blob/main/openautoscopev2/ui/elements.py#L109-L170) is a regular input that only apply's its value, when 'return/enter key press' is done.  
We checked it and it was working as intended described below:
> Changes only take effect after pressing 'return' key. Not while typing.

If that's now how it's working, can you give me specific element names to check them?
